CREATE TABLE IF NOT EXISTS public.transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "desc" TEXT NOT NULL,
    amount NUMERIC NOT NULL,
    type VARCHAR(20) NOT NULL,
    category VARCHAR(100) DEFAULT 'Umum',
    date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_id TEXT
);

CREATE TABLE IF NOT EXISTS public.monthly_budgets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    month CHAR(7) NOT NULL,
    category VARCHAR(100) NOT NULL,
    limit_amount NUMERIC NOT NULL CHECK (limit_amount > 0),
    user_id TEXT,
    UNIQUE (user_id, month, category)
);

CREATE TABLE IF NOT EXISTS public.savings_goals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    target_amount NUMERIC NOT NULL CHECK (target_amount > 0),
    current_amount NUMERIC NOT NULL DEFAULT 0 CHECK (current_amount >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    user_id TEXT
);

CREATE TABLE IF NOT EXISTS public.telegram_processed_updates (
    update_id BIGINT PRIMARY KEY,
    processed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    user_id TEXT
);

CREATE TABLE IF NOT EXISTS public.telegram_link_codes (
    code_hash TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.telegram_user_links (
    telegram_user_id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    linked_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.telegram_webhook_config (
    id BOOLEAN PRIMARY KEY DEFAULT TRUE CHECK (id),
    secret TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS public.legacy_user_migrations (
    legacy_user_id TEXT PRIMARY KEY,
    email TEXT NOT NULL,
    claimed_at TIMESTAMPTZ
);

CREATE UNIQUE INDEX IF NOT EXISTS legacy_user_migrations_email_idx
    ON public.legacy_user_migrations (lower(email), legacy_user_id);
CREATE INDEX IF NOT EXISTS transactions_owner_date_idx
    ON public.transactions (user_id, date DESC, id DESC);
CREATE INDEX IF NOT EXISTS savings_goals_owner_idx
    ON public.savings_goals (user_id, created_at, id);
CREATE INDEX IF NOT EXISTS telegram_user_links_owner_idx
    ON public.telegram_user_links (user_id);
CREATE INDEX IF NOT EXISTS telegram_link_codes_owner_idx
    ON public.telegram_link_codes (user_id, expires_at);

ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.monthly_budgets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.savings_goals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.telegram_link_codes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS transactions_owner_policy ON public.transactions;
CREATE POLICY transactions_owner_policy ON public.transactions
    FOR ALL TO authenticated
    USING (user_id = (SELECT auth.uid()::text))
    WITH CHECK (user_id = (SELECT auth.uid()::text));

DROP POLICY IF EXISTS monthly_budgets_owner_policy ON public.monthly_budgets;
CREATE POLICY monthly_budgets_owner_policy ON public.monthly_budgets
    FOR ALL TO authenticated
    USING (user_id = (SELECT auth.uid()::text))
    WITH CHECK (user_id = (SELECT auth.uid()::text));

DROP POLICY IF EXISTS savings_goals_owner_policy ON public.savings_goals;
CREATE POLICY savings_goals_owner_policy ON public.savings_goals
    FOR ALL TO authenticated
    USING (user_id = (SELECT auth.uid()::text))
    WITH CHECK (user_id = (SELECT auth.uid()::text));

DROP POLICY IF EXISTS telegram_link_codes_owner_policy ON public.telegram_link_codes;
CREATE POLICY telegram_link_codes_owner_policy ON public.telegram_link_codes
    FOR ALL TO authenticated
    USING (user_id = (SELECT auth.uid()::text))
    WITH CHECK (user_id = (SELECT auth.uid()::text));

GRANT USAGE ON SCHEMA public TO authenticated, service_role;
REVOKE ALL ON public.transactions, public.monthly_budgets, public.savings_goals,
    public.telegram_link_codes FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, DELETE ON public.transactions TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.monthly_budgets, public.savings_goals TO authenticated;
GRANT INSERT, DELETE ON public.telegram_link_codes TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.transactions_id_seq,
    public.monthly_budgets_id_seq, public.savings_goals_id_seq TO authenticated;
REVOKE ALL ON public.telegram_processed_updates, public.telegram_user_links,
    public.telegram_webhook_config, public.legacy_user_migrations FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public.claim_legacy_saku_data(p_user_id TEXT, p_email TEXT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
    mapped_user RECORD;
    claimed_count INTEGER := 0;
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM auth.users
        WHERE id::text = p_user_id AND lower(email) = lower(COALESCE(p_email, ''))
    ) THEN
        RAISE EXCEPTION 'Supabase user identity does not match';
    END IF;

    FOR mapped_user IN
        SELECT legacy_user_id
        FROM public.legacy_user_migrations
        WHERE lower(email) = lower(p_email) AND claimed_at IS NULL
        FOR UPDATE
    LOOP
        UPDATE public.transactions SET user_id = p_user_id WHERE user_id = mapped_user.legacy_user_id;
        UPDATE public.monthly_budgets SET user_id = p_user_id WHERE user_id = mapped_user.legacy_user_id;
        UPDATE public.savings_goals SET user_id = p_user_id WHERE user_id = mapped_user.legacy_user_id;
        UPDATE public.telegram_user_links SET user_id = p_user_id WHERE user_id = mapped_user.legacy_user_id;
        UPDATE public.telegram_processed_updates SET user_id = p_user_id WHERE user_id = mapped_user.legacy_user_id;
        UPDATE public.legacy_user_migrations
        SET claimed_at = NOW()
        WHERE legacy_user_id = mapped_user.legacy_user_id;
        claimed_count := claimed_count + 1;
    END LOOP;

    RETURN jsonb_build_object('user_id', p_user_id, 'mappings_claimed', claimed_count);
END;
$$;

CREATE OR REPLACE FUNCTION public.set_telegram_webhook_secret(p_secret TEXT)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
BEGIN
    IF p_secret IS NULL
       OR length(p_secret) < 32
       OR length(p_secret) > 256
       OR p_secret !~ '^[A-Za-z0-9_-]+$' THEN
        RAISE EXCEPTION 'Telegram webhook secret must be 32-256 ASCII letters, digits, underscores, or hyphens';
    END IF;

    INSERT INTO public.telegram_webhook_config (id, secret)
    VALUES (TRUE, p_secret)
    ON CONFLICT (id) DO UPDATE SET secret = EXCLUDED.secret;
END;
$$;

CREATE OR REPLACE FUNCTION public.telegram_link_account(
    p_telegram_user_id TEXT, p_code_hash TEXT, p_secret TEXT
)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
    linked_user_id TEXT;
BEGIN
    IF NOT EXISTS (SELECT 1 FROM public.telegram_webhook_config WHERE id = TRUE AND secret = p_secret) THEN
        RAISE EXCEPTION 'Telegram authorization failed';
    END IF;
    DELETE FROM public.telegram_link_codes
    WHERE code_hash = p_code_hash AND expires_at > NOW()
    RETURNING user_id INTO linked_user_id;
    IF linked_user_id IS NULL THEN RETURN FALSE; END IF;

    INSERT INTO public.telegram_user_links (telegram_user_id, user_id, linked_at)
    VALUES (p_telegram_user_id, linked_user_id, NOW())
    ON CONFLICT (telegram_user_id) DO UPDATE
    SET user_id = EXCLUDED.user_id, linked_at = NOW();
    RETURN TRUE;
END;
$$;

CREATE OR REPLACE FUNCTION public.telegram_get_user(p_telegram_user_id TEXT, p_secret TEXT)
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM public.telegram_webhook_config WHERE id = TRUE AND secret = p_secret) THEN
        RAISE EXCEPTION 'Telegram authorization failed';
    END IF;
    RETURN (SELECT user_id FROM public.telegram_user_links WHERE telegram_user_id = p_telegram_user_id);
END;
$$;

CREATE OR REPLACE FUNCTION public.telegram_unlink_user(p_telegram_user_id TEXT, p_secret TEXT)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE affected INTEGER;
BEGIN
    IF NOT EXISTS (SELECT 1 FROM public.telegram_webhook_config WHERE id = TRUE AND secret = p_secret) THEN
        RAISE EXCEPTION 'Telegram authorization failed';
    END IF;
    DELETE FROM public.telegram_user_links WHERE telegram_user_id = p_telegram_user_id;
    GET DIAGNOSTICS affected = ROW_COUNT;
    RETURN affected > 0;
END;
$$;

CREATE OR REPLACE FUNCTION public.telegram_save_transaction(
    p_telegram_user_id TEXT, p_update_id BIGINT, p_desc TEXT, p_amount NUMERIC,
    p_type TEXT, p_category TEXT, p_secret TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
    owner_id TEXT;
    claimed_id BIGINT;
    saved_row public.transactions%ROWTYPE;
    total_income NUMERIC;
    total_expense NUMERIC;
BEGIN
    IF NOT EXISTS (SELECT 1 FROM public.telegram_webhook_config WHERE id = TRUE AND secret = p_secret) THEN
        RAISE EXCEPTION 'Telegram authorization failed';
    END IF;
    SELECT user_id INTO owner_id FROM public.telegram_user_links WHERE telegram_user_id = p_telegram_user_id;
    IF owner_id IS NULL THEN RAISE EXCEPTION 'Telegram account is not linked'; END IF;
    IF p_update_id IS NULL OR p_update_id < 0
       OR p_desc IS NULL OR length(trim(p_desc)) = 0 OR length(p_desc) > 500
       OR p_amount IS NULL OR p_amount <= 0 OR p_amount > 1000000000000
       OR p_type IS NULL OR p_type NOT IN ('income', 'expense')
       OR length(COALESCE(p_category, 'Umum')) > 100 THEN
        RAISE EXCEPTION 'Invalid Telegram transaction data';
    END IF;

    INSERT INTO public.telegram_processed_updates (update_id, user_id)
    VALUES (p_update_id, owner_id)
    ON CONFLICT (update_id) DO NOTHING
    RETURNING update_id INTO claimed_id;
    IF claimed_id IS NULL THEN RETURN jsonb_build_object('inserted', FALSE); END IF;

    INSERT INTO public.transactions ("desc", amount, type, category, user_id)
    VALUES (p_desc, p_amount, p_type, COALESCE(NULLIF(p_category, ''), 'Umum'), owner_id)
    RETURNING * INTO saved_row;

    SELECT COALESCE(SUM(amount) FILTER (WHERE type = 'income'), 0),
           COALESCE(SUM(amount) FILTER (WHERE type = 'expense'), 0)
    INTO total_income, total_expense
    FROM public.transactions WHERE user_id = owner_id;

    RETURN jsonb_build_object(
        'inserted', TRUE, 'transaction', to_jsonb(saved_row),
        'income', total_income, 'expense', total_expense
    );
END;
$$;

CREATE OR REPLACE FUNCTION public.telegram_get_balance(p_telegram_user_id TEXT, p_secret TEXT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE owner_id TEXT; total_income NUMERIC; total_expense NUMERIC;
BEGIN
    IF NOT EXISTS (SELECT 1 FROM public.telegram_webhook_config WHERE id = TRUE AND secret = p_secret) THEN
        RAISE EXCEPTION 'Telegram authorization failed';
    END IF;
    SELECT user_id INTO owner_id FROM public.telegram_user_links WHERE telegram_user_id = p_telegram_user_id;
    IF owner_id IS NULL THEN RETURN NULL; END IF;
    SELECT COALESCE(SUM(amount) FILTER (WHERE type = 'income'), 0),
           COALESCE(SUM(amount) FILTER (WHERE type = 'expense'), 0)
    INTO total_income, total_expense
    FROM public.transactions WHERE user_id = owner_id;
    RETURN jsonb_build_object('income', total_income, 'expense', total_expense);
END;
$$;

CREATE OR REPLACE FUNCTION public.telegram_get_history(p_telegram_user_id TEXT, p_secret TEXT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE owner_id TEXT; history JSONB;
BEGIN
    IF NOT EXISTS (SELECT 1 FROM public.telegram_webhook_config WHERE id = TRUE AND secret = p_secret) THEN
        RAISE EXCEPTION 'Telegram authorization failed';
    END IF;
    SELECT user_id INTO owner_id FROM public.telegram_user_links WHERE telegram_user_id = p_telegram_user_id;
    IF owner_id IS NULL THEN RETURN NULL; END IF;
    SELECT COALESCE(jsonb_agg(to_jsonb(t) ORDER BY t.date DESC), '[]'::jsonb)
    INTO history
    FROM (
        SELECT id, "desc", amount, type, category, date
        FROM public.transactions WHERE user_id = owner_id
        ORDER BY date DESC, id DESC LIMIT 5
    ) AS t;
    RETURN history;
END;
$$;

CREATE OR REPLACE FUNCTION public.telegram_reset_transactions(p_telegram_user_id TEXT, p_secret TEXT)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE owner_id TEXT;
BEGIN
    IF NOT EXISTS (SELECT 1 FROM public.telegram_webhook_config WHERE id = TRUE AND secret = p_secret) THEN
        RAISE EXCEPTION 'Telegram authorization failed';
    END IF;
    SELECT user_id INTO owner_id FROM public.telegram_user_links WHERE telegram_user_id = p_telegram_user_id;
    IF owner_id IS NULL THEN RETURN FALSE; END IF;
    DELETE FROM public.transactions WHERE user_id = owner_id;
    RETURN TRUE;
END;
$$;

REVOKE ALL ON FUNCTION public.claim_legacy_saku_data(TEXT, TEXT) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.claim_legacy_saku_data(TEXT, TEXT) TO service_role;
REVOKE ALL ON FUNCTION public.set_telegram_webhook_secret(TEXT) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.set_telegram_webhook_secret(TEXT) TO service_role;
REVOKE ALL ON FUNCTION public.telegram_link_account(TEXT, TEXT, TEXT) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.telegram_link_account(TEXT, TEXT, TEXT) TO service_role;
REVOKE ALL ON FUNCTION public.telegram_get_user(TEXT, TEXT) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.telegram_get_user(TEXT, TEXT) TO service_role;
REVOKE ALL ON FUNCTION public.telegram_unlink_user(TEXT, TEXT) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.telegram_unlink_user(TEXT, TEXT) TO service_role;
REVOKE ALL ON FUNCTION public.telegram_save_transaction(TEXT, BIGINT, TEXT, NUMERIC, TEXT, TEXT, TEXT) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.telegram_save_transaction(TEXT, BIGINT, TEXT, NUMERIC, TEXT, TEXT, TEXT) TO service_role;
REVOKE ALL ON FUNCTION public.telegram_get_balance(TEXT, TEXT) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.telegram_get_balance(TEXT, TEXT) TO service_role;
REVOKE ALL ON FUNCTION public.telegram_get_history(TEXT, TEXT) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.telegram_get_history(TEXT, TEXT) TO service_role;
REVOKE ALL ON FUNCTION public.telegram_reset_transactions(TEXT, TEXT) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.telegram_reset_transactions(TEXT, TEXT) TO service_role;

NOTIFY pgrst, 'reload schema';
